spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sfg_dev
    username: sfg_dev_user
    password: T=6He6X?n?(#Y8$
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true
    defer-datasource-initialization: true
  #    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql
  sql:
    init:
      platform: mysql
