# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.8-browsers

    working_directory: ~/~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn clean install -Dskiptests

      - run:
          name: Run Tests
          command: mvn test